<a href="https://colab.research.google.com/github/prabalai/pytorch/blob/main/pytorch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning PyTorch Tensors: Introduction and Creation



# 1. Introduction to Tensors

## What is a Tensor?
A **tensor** is a multi-dimensional array, similar to NumPy arrays, but optimized for high-performance computing. Tensors are the building blocks of deep learning frameworks like PyTorch.

## Why Use Tensors in Deep Learning?
Tensors are essential in deep learning because:
- They can efficiently handle multi-dimensional data like scalars, vectors, and matrices.
- PyTorch tensors support GPU acceleration, making computations faster.
- They allow for automatic differentiation, which is critical for training deep learning models.

## How Tensors Help in Deep Learning
- Represent input data like images, text, and audio.
- Store weights and biases of neural networks.
- Perform matrix operations required for forward and backward propagation.
---

# 2. Creating Tensors in PyTorch



In [30]:
import torch
print (torch.__version__)


2.5.1+cu121


In [31]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[-4.3446e-09,  3.3340e-41,  1.2659e-08],
        [ 4.3374e-41,  8.9683e-44,  0.0000e+00]])


In [32]:
# check type
type(a)

torch.Tensor

In [33]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
#using rand
torch.rand(2,3)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [36]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [37]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [38]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])



## Tensor Shapes

In [40]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
x.shape

torch.Size([2, 3])

In [42]:
torch.empty_like(x)#for creating same space tensor which is empty

tensor([[              0, 102188841310368, 102188817665168],
        [132939371792240,               0,               0]])

In [43]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [45]:
torch.rand_like(x, dtype=torch.float32)#changing data type because rand function generate only float values and our x is int type

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [46]:
!git clone https://github.com/prabalai/pytorch.git


fatal: destination path 'pytorch' already exists and is not an empty directory.


In [47]:
%ls /content/


pytorch/  sample_data/


In [48]:
%ls /content/pytorch/


README.md


In [49]:
%ls /content/


pytorch/  sample_data/


In [55]:
%ls /content/


pytorch/  pytorch_tensor_basics.ipynb


In [56]:
!cp /content/pytorch-tensor-basics.ipynb/content/pytorch/


cp: missing destination file operand after '/content/pytorch-tensor-basics.ipynb/content/pytorch/'
Try 'cp --help' for more information.


In [57]:
%ls /content/pytorch/



README.md


In [58]:
!cp /content/your_notebook.ipynb /content/pytorch/


cp: cannot stat '/content/your_notebook.ipynb': No such file or directory
